AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Sample Template SQS template showing how to create an SQS queue. **WARNING** This template creates an Amazon SQS queue and one or more Amazon CloudWatch alarms. You will be billed for the AWS resources used if you create a stack from this template."
Parameters: 
  SQSQueueName: 
    Default: "lifecycle_hook_sqs_autoscaling_queue"
    Description: "SQS queue name used to receive autoscaling lifecycle events"
    Type: "String"
Resources: 
  MyQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: 
        Ref: "SQSQueueName"
Outputs: 
  QueueURL: 
    Description: "URL of newly created SQS Queue"
    Value: 
      Ref: "MyQueue"
  QueueARN: 
    Description: "ARN of newly created SQS Queue"
    Value: 
      Fn::GetAtt: 
        - "MyQueue"
        - "Arn"
  QueueName: 
    Description: "Name newly created SQS Queue"
    Value: 
      Fn::GetAtt: 
        - "MyQueue"
        - "QueueName"
